language: go
go:
    - tip

before_install:
    - go get github.com/mattn/goveralls
    - go get github.com/golang/dep

install:
    - $GOPATH/bin/dep ensure

script:
    - go get -t -d -v ./...
    - go build -v
